---
- hosts: localhost
  become: true
  become_user: ttpl56
  become_method: sudo
  vars:
    ansible_become_pass: pw4ttpl056
  tasks:
  - name: Create npm global directory
    file:
      path: "/usr/local/lib/npm"
      owner: "root"
      group: "root"
      state: directory

  - name: Add npm_config_prefix bin directory to global $PATH.
    template:
      src: npm.sh.j2
      dest: /etc/profile.d/npm.sh
      mode: 0644

  - name: Ensure npm global packages are installed.
    npm:
      name: "{{ item.name | default(item) }}"
      version: "{{ item.version | default('latest') }}"
      global: yes
      state: latest
    environment:
      NPM_CONFIG_PREFIX: "/usr/local/lib/npm"
      NODE_PATH: "/usr/local/lib/npm/lib/node_modules"
      NPM_CONFIG_UNSAFE_PERM: "false"
    with_items:
      - "grunt-cli"

  - name: Install packages defined in a given package.json.
    npm:
      path: ""
