---
- hosts: localhost
  become: true
  become_user: ttpl56
  become_method: sudo
  tasks:
  - name: Install list of packages
    apt: pkg={{ item }} state=installed
    with_items:
       - "npm"
       - "nodejs"
       - "grunt-cli"
