---
- hosts: localhost
  tasks:
  - name: Create npm global directory
    file:
      path: "/usr/local/lib/npm"
      owner: "root"
      group: "root"
      state: directory
    become: yes
    become_user: ttpl56

