---
- name: Get Jenkins crumb
  uri:
    user: vaibhavTekdi
    password: "Tekdi@2018"
    force_basic_auth: yes
    url: "http://localhost:8080/crumbIssuer/api/json"
    return_content: yes
  register: crumb_token
  until: crumb_token.content.find('Please wait while Jenkins is getting ready') == -1
  tags: [jenkins]

- name: Plugins are installed
  uri:
    url: "http://localhost:8080/pluginManager/installNecessaryPlugins"
    method: POST
    user: admin
    password: "Tekdi@2018"
    body: '<jenkins><install plugin="{{ item }}@latest" /></jenkins>'
    headers:
      Content-Type: "text/xml"
      Jenkins-Crumb: "{{ crumb_token.json.crumb }}"
    creates: "/var/lib/jenkins/plugins/{{ item }}"
  with_items:
    - "git"
    - "copyArtifacts"
    - "github-branch-source"
    - "github"
  tags: [jenkins]

- wait_for:
    path: "/var/lib/jenkins/plugins/{{ item }}"
  with_items:
    - "git"
    - "copyArtifacts"
    - "github-branch-source"
    - "github"
  tags: [jenkins]
