---
- hosts: localhost
  become: false
  vars_files: ["secrets/ssh_passwords"]
  tasks:
  - name: Install plugin
    set_fact:
      jenkins_admin_password: "{{ jenkins_admin_password }}"
      no_log: True

  - name: Install Jenkins plugins using password.
    jenkins_plugin:
      name: "{{ item }}"
      jenkins_home: "{{ jenkins_home }}"
      url_username: "{{ jenkins_username }}"
      url_password: "{{ jenkins_password }}"
      timeout: "30"
      updates_expiration: "86400"
      url: "http://{{jenkins_host}}:8080"
      with_dependencies: "yes"
    with_items:
      - "ansible"
      - "copyartifact"
      - "github"
      - "github-branch-source"
      - "nodejs"
    when: jenkins_admin_password != ""

  - name: Create npm global directory
    file:
      path: "/usr/local/lib/npm"
      owner: "root"
      group: "root"
      state: directory

  - name: Add npm_config_prefix bin directory to global $PATH.
    template:
      src: npm.sh.j2
      dest: /etc/profile.d/npm.sh
      mode: 0644

  - name: Ensure npm global packages are installed.
    npm:
      name: "{{ item.name | default(item) }}"
      version: "{{ item.version | default('latest') }}"
      global: yes
      state: latest
    environment:
      NPM_CONFIG_PREFIX: "/usr/local/lib/npm"
      NODE_PATH: "/usr/local/lib/npm/lib/node_modules"
      NPM_CONFIG_UNSAFE_PERM: "false"
    with_items:
      - "grunt-cli"

  - name: Install packages defined in a given package.json.
    npm:
      path: ""
