---
- hosts: all
  become: false
  vars:
    workspace: "{{ lookup('env','WORKSPACE') }}"
  vars_files: ["secrets/{{site_id}}","secrets/ssh_passwords"]
  tasks:
  - name: Install Jenkins plugins.
    jenkins_plugin:
      name: "{{ item }}"
      jenkins_home: "/var/lib/jenkins/"
      timeout: "30"
      updates_expiration: "86400"
      url: "http://localhost:8080"
      with_dependencies: "yes"
    with_items:
      - "copyArtifacts"
      - "github-branch-source"
    notify: restart jenkins
