---
- hosts: localhost
  become: false
  tasks:
  - name: Install plugin
    set_fact:
      jenkins_admin_password: "AQAAABAAAAAQWdNNuRiVEfnv53EUQHzhhHkG1Fmmpfv2a6YCyN"
      no_log: True

  - name: Install Jenkins plugins using password.
    jenkins_plugin:
      name: "{{ item }}"
      jenkins_home: "/var/lib/jenkins/"
      url_username: "vaibhavTekdi"
      url_password: "Tekdi@2018"
      timeout: "30"
      updates_expiration: "86400"
      url: "http://localhost:8080"
      with_dependencies: "yes"
    with_items:
      - "ansible"
      - "copyartifact"
      - "github-branch-source"
    when: jenkins_admin_password != ""
