---
- hosts: localhost
  become: false
  vars_files: ["secrets/ssh_passwords"]
  tasks:
  - name: Install plugin
    set_fact:
      jenkins_admin_password: "{{ jenkins_admin_password }}"
      no_log: True

  - name: Install Jenkins plugins using password.
    jenkins_plugin:
      name: "{{ item }}"
      jenkins_home: "{{ jenkins_home }}"
      url_username: "{{ jenkins_username }}"
      url_password: "{{ jenkins_password }}"
      timeout: "30"
      updates_expiration: "86400"
      url: "http://{{jenkins_host}}:8080"
      with_dependencies: "yes"
    with_items:
      - "ansible"
      - "copyartifact"
      - "github"
      - "github-branch-source"
      - "nodejs"
    when: jenkins_admin_password != ""

  - name: Node.js | Add the node.js PPA
    apt_repository: repo=ppa:chris-lea/node.js
    tags: nodejs

  - name: Node.js | Install nodejs and npm
    apt: pkg=nodejs update_cache=yes
    tags: nodejs

  - name: Node.js | Install packages
    command: npm install -g $item
    with_items:
      - grunt-cli
