---
- hosts: localhost
  become: false
  vars:
    my_jenkins_plugins:
      token-macro:
        enabled: yes
      ansible:
        enabled: yes
      copyartifact:
        enabled: yes
      github:
        enabled: yes
      github-branch-source:
        enabled: yes
      nodejs:
        enabled: yes
  vars_files: ["secrets/ssh_passwords"]
  tasks:
    - name: Install plugins
      jenkins_plugin:
        name: "{{ item.key }}"
      with_dict: "{{ my_jenkins_plugins }}"
