---
- hosts: localhost
  become: false
  vars_files: ["secrets/ssh_passwords"]
  tasks:
  - name: Install Jenkins plugins
    command:
      java -jar jenkins-cli.jar -s http://localhost:8080 install-plugin {{ item }}
      creates=/var/lib/jenkins/plugins/{{ item }}.jpi
    with_items:
      - "ansible"
      - "copyartifact"
      - "github"
      - "github-branch-source"
      - "nodejs"
